import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

export const POLICY_FAMILIES = [
  'vdp',
  'vdp-with-cvd',
  'safe-harbor',
  'simple-safe-harbor',
] as const

export type PolicyFamily = (typeof POLICY_FAMILIES)[number]

export type PolicySource = {
  revision: string
  locales: string[]
  policies: Record<PolicyFamily, Record<string, string>>
}

export function stripProvenance(markdown: string): string {
  return markdown.replace(/^\uFEFF?\s*<!--[\s\S]*?-->\s*\n?/, '')
}

function resolveRevision(sourceRoot: string): string {
  return execFileSync('git', ['-C', sourceRoot, 'rev-parse', 'HEAD'], {
    encoding: 'utf8',
  }).trim()
}

export function loadPolicySource(projectRoot = process.cwd()): PolicySource {
  const sourceRoot = join(projectRoot, 'vendor', 'dioterms')
  const termsRoot = join(sourceRoot, 'terms')
  const manifestPath = join(termsRoot, 'languages.json')

  if (!existsSync(manifestPath)) {
    throw new Error('DIOTerms is not checked out. Run `git submodule update --init`.')
  }

  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as { languages?: unknown }
  if (!Array.isArray(manifest.languages) || !manifest.languages.every((locale) => typeof locale === 'string')) {
    throw new Error('DIOTerms terms/languages.json must contain a string `languages` array.')
  }

  const locales = [...manifest.languages]
  const policies = Object.fromEntries(
    POLICY_FAMILIES.map((family) => {
      const localized = Object.fromEntries(
        locales.map((locale) => {
          const sourcePath = join(termsRoot, family, `${locale}.md`)
          if (!existsSync(sourcePath)) {
            throw new Error(`DIOTerms is missing ${family}/${locale}.md`)
          }

          return [locale, stripProvenance(readFileSync(sourcePath, 'utf8'))]
        }),
      )

      return [family, localized]
    }),
  ) as PolicySource['policies']

  return {
    revision: resolveRevision(sourceRoot),
    locales,
    policies,
  }
}

export function serializePolicyModule(source: PolicySource): string {
  return [
    '// Generated by scripts/generate-policy-source.ts from vendor/dioterms.',
    '// Do not edit this file; update the submodule pin instead.',
    `export const policySource = ${JSON.stringify(source, null, 2)} as const`,
    '',
    'export type SupportedLocale = keyof typeof policySource.policies.vdp',
    'export type PolicyFamily = keyof typeof policySource.policies',
    '',
  ].join('\n')
}
